### ISSUE TITLE
HA mode creates OIFITS empty of actual data

### ISSUE THREAD

**Issue by fabienbaron** [bkloppenborg/oifits-sim#1]
Go to ./oifits-sim/bin and do:
./oifits-sim -t ../samples/target_epsAur.txt -i ../samples/2010-10.fits -o output.oifits -a CHARA -c MIRC -m LowH -obs ../samples/obs_ha_example.txt

Expected result: points at all 3 HA in obs_ha_example.txt
Current result: no data in the OIFITS

**Comment by fabienbaron** [comment]
Tried to bisect and found that the first bad commit could be any of:
79f587ba244efabe649712da35a48ab0b2f27286
373bd5805e7029db71e58c72b0850a63d2580592
4e4f2dea8b24968a92c4f03ac8b67d7d93a9fab4
c4143ae47f0b19b56757203d41d59f06d87d40b7

**Comment by bkloppenborg** [comment]
Closed by #2
